source 'https://rubygems.org'

ruby '2.2.1'

gem 'alert_message'
gem 'activerecord-session_store', github: 'rails/activerecord-session_store'
gem 'actionpack-action_caching'
gem 'bourbon'
gem 'bootstrap-wysihtml5-rails-font-awesome', '~> 0.3.1.25'
gem 'breadcrumbs_on_rails'
gem 'bitters'
gem 'carrierwave'
gem 'cancancan'
gem 'coffee-rails', '~> 4.1.0'
gem 'chartkick'
gem 'devise'
gem 'figaro'
gem 'friendly_id'
gem 'htmlcompressor', '~> 0.2.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-infinite-pages', git: 'git://github.com/luizpicolo/jquery-infinite-pages.git'
gem 'letsrate', git: 'git://github.com/luizpicolo/letsrate.git'
gem 'mini_magick'
gem 'modernizr-rails'
gem 'neat'
gem 'owlcarousel-rails'
gem 'omniauth-facebook'
gem 'pg'
gem 'rails-observers'
gem 'rails', '4.2.4'
gem 'rails-i18n'
gem 'rails-env'
gem 'rails_admin', git: 'git://github.com/luizpicolo/rails_admin.git'
gem 'randumb'
gem 'responders'
gem 'sass-rails'
gem 'searchkick'
gem 'seed_dump'
gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'binding_of_caller'
  # gem 'capybara'
  gem 'database_rewinder'
  gem 'email_spec'
  gem 'factory_girl_rails', require: false
  gem 'faker'
  gem 'mina'
  gem 'rspec-rails', require: 'rspec/rails'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'spring'
  gem 'rename'
  gem 'rails_db_info'
  gem 'web-console'
  gem 'simplecov', require: false
end

group :staging, :production do
  gem 'passenger'
  gem 'therubyracer'
  gem 'newrelic_rpm'
end

group :production do
  gem 'turnout'
end
