# Seeds
puts 'Seed first user'
User.create([
  { email: 'luizpicolo@gmail.com', password: '12345678', password_confirmation: '12345678', admin: true },
  { email: 'danilo.mikucki@gmail.com', password: '12345678', password_confirmation: '12345678', admin: true }
])

puts 'Seed categories ------->'
ProductCategory.create([
  { name: 'Açougue' },
  { name: 'Bebidas' },
  { name: 'Higiene & Perfumaria' },
  { name: 'Hortifruti' },
  { name: 'Limpeza' },
  { name: 'Mercearia' },
  { name: 'Padaria' }
])

puts 'Seed subcategories -------->'
ProductSubcategory.create([
  { name: 'Acessórios para Churrasco',  product_category_id: 1 },
  { name: 'Cortes Especiais Bovino',    product_category_id: 1 },
  { name: 'Cortes Especiais Frango',    product_category_id: 1 },
  { name: 'Cortes Especiais Suíno',     product_category_id: 1 },

  { name: 'Aguardentes',                product_category_id: 2 },
  { name: 'Águas',                      product_category_id: 2 },
  { name: 'Bebidas à Base de Soja',     product_category_id: 2 },
  { name: 'Cervejas',                   product_category_id: 2 },
  { name: 'Cervejas Especiais',         product_category_id: 2 },
  { name: 'Chá Pronto',                 product_category_id: 2 },
  { name: 'Destilados',                 product_category_id: 2 },
  { name: 'Isotônicos & Energéticos',   product_category_id: 2 },
  { name: 'Licores',                    product_category_id: 2 },
  { name: 'Refrescos',                  product_category_id: 2 },
  { name: 'Refrigerantes',              product_category_id: 2 },
  { name: 'Sucos',                      product_category_id: 2 },

  { name: 'Absorventes',                product_category_id: 3 },
  { name: 'Absorventes',                product_category_id: 3 },
  { name: 'Barba & Depilação',          product_category_id: 3 },
  { name: 'Condicionadores',            product_category_id: 3 },
  { name: 'Cremes para Cabelo',         product_category_id: 3 },
  { name: 'Cuidados com a Pele',        product_category_id: 3 },
  { name: 'Desodorantes',               product_category_id: 3 },
  { name: 'Fraldas Descatáveis',        product_category_id: 3 },
  { name: 'Higiene Oral',               product_category_id: 3 },
  { name: 'Infantil',                   product_category_id: 3 },
  { name: 'Manicure',                   product_category_id: 3 },
  { name: 'Papeis Higiênicos',          product_category_id: 3 },
  { name: 'Protetores Solar',           product_category_id: 3 },
  { name: 'Sabonetes',                  product_category_id: 3 },
  { name: 'Saúde & Cuidados Especiais', product_category_id: 3 },
  { name: 'Shampoos',                   product_category_id: 3 },

  { name: 'Folhagens',                  product_category_id: 4 },
  { name: 'Frutas',                     product_category_id: 4 },
  { name: 'Legumes & Verduras',         product_category_id: 4 },

  { name: 'Ceras & Cia',                product_category_id: 5 },
  { name: 'Desinfetantes',              product_category_id: 5 },
  { name: 'Inseticidas & Raticidas',    product_category_id: 5 },
  { name: 'Limpeza de Cozinha',         product_category_id: 5 },
  { name: 'Limpeza de Roupa',           product_category_id: 5 },
  { name: 'Limpeza Geral',              product_category_id: 5 },
  { name: 'Purificadores de Ar',        product_category_id: 5 },

  { name: 'Achocolatados',              product_category_id: 6 },
  { name: 'Açúcares',                   product_category_id: 6 },
  { name: 'Adoçantes',                  product_category_id: 6 },
  { name: 'Alimento Infantil',          product_category_id: 6 },
  { name: 'Arroz & Feijão',             product_category_id: 6 },
  { name: 'Azeites',                    product_category_id: 6 },
  { name: 'Balas & Chicletes',          product_category_id: 6 },
  { name: 'Biscoitos',                  product_category_id: 6 },
  { name: 'Cafés & Cia',                product_category_id: 6 },
  { name: 'Caldos',                     product_category_id: 6 },
  { name: 'Catchup & Mostardas',        product_category_id: 6 },
  { name: 'Cereais Matinais',           product_category_id: 6 },
  { name: 'Chás',                       product_category_id: 6 },
  { name: 'Chocolates',                 product_category_id: 6 },
  { name: 'Chocolates Especiais',       product_category_id: 6 },
  { name: 'Conservas',                  product_category_id: 6 },
  { name: 'Conservas Doces',            product_category_id: 6 },
  { name: 'Diet & Light',               product_category_id: 6 },
  { name: 'Doces, Goiabadas & Cia',     product_category_id: 6 },
  { name: 'Farinhas & Cia',             product_category_id: 6 },
  { name: 'Gelatinas & Cia',            product_category_id: 6 },
  { name: 'Geleias',                    product_category_id: 6 },
  { name: 'Ingredientes Doces',         product_category_id: 6 },
  { name: 'Leites em Pó',               product_category_id: 6 },
  { name: 'Leites Longa Vida',          product_category_id: 6 },
  { name: 'Maioneses',                  product_category_id: 6 },
  { name: 'Massas',                     product_category_id: 6 },
  { name: 'Massas Instantâneas',        product_category_id: 6 },
  { name: 'Misturas de Bolo',           product_category_id: 6 },
  { name: 'Molhos de Tomate',           product_category_id: 6 },
  { name: 'Molhos Diversos',            product_category_id: 6 },
  { name: 'Óleos de Soja & Cia',        product_category_id: 6 },
  { name: 'Pipocas & Cia',              product_category_id: 6 },
  { name: 'Produtos Orientais',         product_category_id: 6 },
  { name: 'Salgadinhos & Snacks',       product_category_id: 6 },
  { name: 'Sardinhas, Atuns & Cia',     product_category_id: 6 },
  { name: 'Sopas & Cremes',             product_category_id: 6 },
  { name: 'Temperos',                   product_category_id: 6 },
  { name: 'Torradas & Cia',             product_category_id: 6 },

  { name: 'Bolos',                      product_category_id: 7 },
  { name: 'Doces',                      product_category_id: 7 },
  { name: 'Pães',                       product_category_id: 7 },
  { name: 'Pães Industrializados',      product_category_id: 7 },
  { name: 'Salgadinhos',                product_category_id: 7 },
])
